import Head from 'next/head';
import type { ReactElement } from 'react';
import Layout from '../components/layouts/rootLayout/Layout';
import OFirmieContent from '../components/pagesComponents/o-firmie/OFirmieContent';
import type { NextPageWithLayout } from './_app';

const HomePage: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Famatel Polska</title>
      </Head>
      <OFirmieContent />
    </>
  );
};

HomePage.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default HomePage;

/*****************************************************************************/
// const Home: NextPage = () => {
//   return (
//     <>
//       <Head>
//         <title>Famatel </title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       {/* <HomeLayout /> */}
//       <div>......................</div>
//     </>
//   );
// };

// export default Home;
