// import Head from 'next/head';
import type { ReactElement } from 'react';
import Layout from '../components/layouts/rootLayout/Layout';
// import NestedLayout from '../components/layouts/pagesLayouts/homeLayout/HomeLayout';
import type { NextPageWithLayout } from './_app';

const HomePage: NextPageWithLayout = () => {
  return (
    // <>
    //   <Head>
    //     <title>Famatel Polska</title>
    //     <meta />
    //   </Head>
    <div className="relative">
      <div className="fc h-[50vh] bg-greyShade2 px-4">
        <p className="text-3xl text-corpo">
          At Famatel we have the knowledge, experience and technology necessary
          to develop new electrical solutions that meet the needs of the sector
          śćążźół.
        </p>{' '}
      </div>
      <div className="h-[50vh] bg-dark"></div>
      <div className="h-[50vh] bg-amber-400"></div>
    </div>
    // </>
  );
};

HomePage.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {/* <NestedLayout>{page}</NestedLayout> */}
      {page}
    </Layout>
  );
};

export default HomePage;

/*****************************************************************************/
// const Home: NextPage = () => {
//   return (
//     <>
//       <Head>
//         <title>Famatel </title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       {/* <HomeLayout /> */}
//       <div>......................</div>
//     </>
//   );
// };

// export default Home;
