import type { ReactElement } from 'react';
import Layout from '../components/layouts/rootLayout/Layout';
// import NestedLayout from '../components/layouts/pagesLayouts/homeLayout/HomeLayout';
import type { NextPageWithLayout } from './_app';

const HomePage: NextPageWithLayout = () => {
  return (
    <div className="relative">
      <div className="h-[50vh] bg-greyShade2"> </div>
      <div className="h-[50vh] bg-dark"></div>
      <div className="h-[50vh] bg-amber-400"></div>
    </div>
  );
};

HomePage.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {/* <NestedLayout>{page}</NestedLayout> */}
      {page}
    </Layout>
  );
};

export default HomePage;

/*****************************************************************************/
// const Home: NextPage = () => {
//   return (
//     <>
//       <Head>
//         <title>Famatel </title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       {/* <HomeLayout /> */}
//       <div>......................</div>
//     </>
//   );
// };

// export default Home;
